
    /*
     * Generated by Nikku4211's Wavefront to Varooom Converter
     * Nikku4211 - github.com/nikku4211/
     *
     */

    #ifndef FR_MODEL_3D_ITEMS_asteroid1_H
    #define FR_MODEL_3D_ITEMS_asteroid1_H

    #include "fr_model_3d_item.h"

    namespace fr::model_3d_items
    {
        constexpr inline vertex_3d asteroid1_vertices[] = {
             vertex_3d(4.03772,4.03772,4.03772),
             vertex_3d(-4.03772,4.4937,-2.10934),
             vertex_3d(-4.06688,4.03772,6.23921),
             vertex_3d(-3.1921,-2.31814,4.03772),
             vertex_3d(2.28618,-0.7004199999999999,-2.4862),
       };
    constexpr inline bn::color asteroid1_colors[] = {
             bn::color(1,0,0),
    };
    constexpr inline int asteroid1_color_0 = 0;

    constexpr inline face_3d asteroid1_faces_full[] = {
        face_3d(asteroid1_vertices, vertex_3d(-0.9911,-0.1327,-0.0107),3,2,1,0,3),
        face_3d(asteroid1_vertices, vertex_3d(0.0148,0.9984,0.0546),0,1,2,0,5),
        face_3d(asteroid1_vertices, vertex_3d(0.2512,-0.2857,0.9248),3,0,2,0,2),
        face_3d(asteroid1_vertices, vertex_3d(-0.5309,-0.6031,-0.5953),1,4,3,0,0),
        face_3d(asteroid1_vertices, vertex_3d(0.6196,-0.7048,0.3455),3,4,0,0,7),
        face_3d(asteroid1_vertices, vertex_3d(0.4888,0.6382,-0.5948),4,1,0,0,1),
    };
    constexpr inline model_3d_item asteroid1_full(asteroid1_vertices, asteroid1_faces_full, asteroid1_colors);
    };
#endif