
/*
 * Generated by Nikku4211's Wavefront to Varooom Converter
 * Nikku4211 - github.com/nikku4211/
 *
 */

#ifndef FR_MODEL_3D_ITEMS_bush_H
#define FR_MODEL_3D_ITEMS_bush_H

#include "fr_model_3d_item.h"

namespace fr::model_3d_items
{
    constexpr inline vertex_3d bush_vertices[] = {
        vertex_3d(14.142140000000001, -0.42761, -8.270809999999999),
        vertex_3d(-14.142140000000001, -0.42761, -8.270809999999999),
        vertex_3d(0.0, 11.269070000000001, -0.32175000000000004),
        vertex_3d(0.0, 0.02741, 16.21986),
        vertex_3d(-14.142140000000001, 5.62083, -8.270809999999999),
        vertex_3d(0.0, 6.075850000000001, 16.21987),
    };
    constexpr inline bn::color bush_colors[] = {
        bn::color(0, 24, 0),
    };
    constexpr inline int bush_color_0 = 0;

    constexpr inline face_3d bush_faces_full[] = {
        face_3d(bush_vertices, vertex_3d(0.0, 0.5620835945734859, -0.8270804269908394), 1, 2, 0, 0, 7),
        face_3d(bush_vertices, vertex_3d(0.7071065638628524, 0.5848345700180145, 0.3974529318723336), 0, 2, 3, 0, 6),
        face_3d(bush_vertices, vertex_3d(-0.7071065638628525, 0.5848345700180145, 0.39745293187233366), 3, 2, 1, 0, 5),
    };
    constexpr inline model_3d_item bush_full(bush_vertices, bush_faces_full);
};
#endif