
    /*
     * Generated by Nikku4211's Wavefront to Varooom Converter
     * Nikku4211 - github.com/nikku4211/
     *
     */

    #ifndef FR_MODEL_3D_ITEMS_player_ship_01_H
    #define FR_MODEL_3D_ITEMS_player_ship_01_H

    #include "fr_model_3d_item.h"

    namespace fr::model_3d_items
    {
        constexpr inline vertex_3d player_ship_01_vertices[] = {
             vertex_3d(0.0,-4.4287399999999995,0.0),
             vertex_3d(-0.0,4.61213,0.48932000000000003),
             vertex_3d(-0.0,-0.0,-22.651780000000002),
             vertex_3d(0.0,0.0,6.47575),
             vertex_3d(-6.47575,-0.0,0.0),
             vertex_3d(6.47575,0.0,-0.0),
             vertex_3d(5.54701,0.0,-3.24867),
             vertex_3d(-5.54701,-0.0,-3.24867),
             vertex_3d(-0.0,5.54218,-3.24867),
             vertex_3d(-17.05645,-8.27965,1.97597),
             vertex_3d(-17.05645,8.27965,1.97597),
             vertex_3d(-7.31155,0.0,29.353099999999998),
             vertex_3d(-23.31047,-0.0,-4.886150000000001),
             vertex_3d(-19.72101,-0.0,16.06829),
             vertex_3d(-11.503060000000001,0.0,-0.16313),
             vertex_3d(17.05645,-8.27965,1.97597),
             vertex_3d(17.05645,8.27965,1.97597),
             vertex_3d(7.31155,-0.0,29.353099999999998),
             vertex_3d(23.31047,0.0,-4.886150000000001),
             vertex_3d(19.72101,0.0,16.06829),
             vertex_3d(11.503060000000001,0.0,-0.16313),
             vertex_3d(9.25632,-1.3017,-1.7369599999999998),
             vertex_3d(9.25632,1.3017,-1.7369599999999998),
             vertex_3d(11.34425,0.0,-1.7369599999999998),
             vertex_3d(7.1683900000000005,0.0,-1.7369599999999998),
             vertex_3d(9.25632,0.0,-3.8248900000000003),
             vertex_3d(9.25632,0.0,0.35097),
             vertex_3d(-9.25632,-1.3017,-1.7369599999999998),
             vertex_3d(-9.25632,1.3017,-1.7369599999999998),
             vertex_3d(-11.34425,0.0,-1.7369599999999998),
             vertex_3d(-7.1683900000000005,0.0,-1.7369599999999998),
             vertex_3d(-9.25632,0.0,-3.8248900000000003),
             vertex_3d(-9.25632,-0.0,0.35097),
       };
    constexpr inline bn::color player_ship_01_colors[] = {
             bn::color(24,24,24),
    };
    constexpr inline int player_ship_01_color_0 = 0;

    constexpr inline face_3d player_ship_01_faces_full[] = {
        face_3d(player_ship_01_vertices, vertex_3d(0.5210,0.6762,0.5210),1,3,5,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.5573,-0.8149,-0.1593),0,2,6,5,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.5573,-0.8149,-0.1593),2,0,4,7,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.4916,-0.7188,0.4916),5,3,0,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.6928,0.6934,-0.1981),8,2,7,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.5210,0.6762,0.5210),3,1,4,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4916,-0.7188,0.4916),3,4,0,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.6455,0.7636,0.0158),6,8,1,5,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.6928,0.6934,-0.1981),2,8,6,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.6455,0.7636,0.0158),1,8,7,4,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.8435,0.5174,0.1445),10,12,13,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4254,-0.8131,0.3973),9,11,13,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.8435,-0.5174,0.1445),13,12,9,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.8109,0.5737,-0.1152),10,11,14,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4254,0.8131,0.3973),11,10,13,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.3594,-0.0000,-0.9332),14,9,10,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.8109,-0.5737,-0.1152),9,14,11,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.7391,-0.0000,-0.6736),10,9,12,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.8435,-0.5174,-0.1445),16,18,19,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4254,0.8131,-0.3973),15,17,19,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.8435,0.5174,-0.1445),19,18,15,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.8109,-0.5737,0.1152),16,17,20,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4254,-0.8131,-0.3973),17,16,19,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.3594,-0.0000,0.9332),20,15,16,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.8109,0.5737,0.1152),15,20,17,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.7391,-0.0000,0.6736),16,15,18,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4676,0.7501,0.4676),22,24,26,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.4676,-0.7501,0.4676),21,23,26,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.4676,-0.7501,-0.4676),23,21,25,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4676,-0.7501,0.4676),26,24,21,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.4676,0.7501,-0.4676),22,23,25,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4676,0.7501,-0.4676),24,22,25,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(-0.4676,-0.7501,-0.4676),24,25,21,0,7),
        face_3d(player_ship_01_vertices, vertex_3d(0.4676,0.7501,0.4676),23,22,26,0,7),
    };
    constexpr inline model_3d_item player_ship_01_full(player_ship_01_vertices, player_ship_01_faces_full);
    };
#endif