
    /*
     * Generated by Nikku4211's Wavefront to Varooom Converter
     * Nikku4211 - github.com/nikku4211/
     *
     */

    #ifndef FR_MODEL_3D_ITEMS_player_ship_02_H
    #define FR_MODEL_3D_ITEMS_player_ship_02_H

    #include "fr_model_3d_item.h"

    namespace fr::model_3d_items
    {
        constexpr inline vertex_3d player_ship_02_vertices[] = {
             vertex_3d(14.33492,-9.65124,-10.586960000000001),
             vertex_3d(7.46359,-1.54274,16.79017),
             vertex_3d(20.13109,-4.63947,3.50536),
             vertex_3d(23.79519,-5.5352,-17.44907),
             vertex_3d(16.78669,-5.1268400000000005,-10.586960000000001),
             vertex_3d(11.74226,-2.58872,-12.72605),
             vertex_3d(11.549069999999999,11.735880000000002,-10.586960000000001),
             vertex_3d(6.87848,2.94916,16.79017),
             vertex_3d(18.55292,7.47626,3.50536),
             vertex_3d(21.929769999999998,8.78574,-17.44907),
             vertex_3d(15.13332,7.56617,-10.586960000000001),
             vertex_3d(10.82173,4.47827,-12.72605),
             vertex_3d(-14.33492,-9.65124,-10.586960000000001),
             vertex_3d(-7.46359,-1.54274,16.79017),
             vertex_3d(-20.13109,-4.63947,3.50536),
             vertex_3d(-23.79519,-5.5352,-17.44907),
             vertex_3d(-16.78669,-5.1268400000000005,-10.586960000000001),
             vertex_3d(-11.74226,-2.58872,-12.72605),
             vertex_3d(-11.54906,11.735880000000002,-10.586960000000001),
             vertex_3d(-6.87848,2.94916,16.79017),
             vertex_3d(-18.55292,7.47626,3.50536),
             vertex_3d(-21.929759999999998,8.78574,-17.44907),
             vertex_3d(-15.13332,7.56617,-10.586960000000001),
             vertex_3d(-10.82173,4.47827,-12.72605),
             vertex_3d(0.0,4.61213,0.48932000000000003),
             vertex_3d(0.0,-0.0,6.47575),
             vertex_3d(6.47575,0.0,0.0),
             vertex_3d(0.0,-4.4287399999999995,-0.0),
             vertex_3d(0.0,0.0,-22.651780000000002),
             vertex_3d(5.54701,0.0,-3.24867),
             vertex_3d(-6.47575,0.0,0.0),
             vertex_3d(-5.54701,0.0,-3.24867),
             vertex_3d(0.0,5.54218,-3.24867),
             vertex_3d(9.25632,1.3017,-1.7369599999999998),
             vertex_3d(7.1683900000000005,0.0,-1.7369599999999998),
             vertex_3d(9.25632,-0.0,0.35097),
             vertex_3d(9.25632,-1.3017,-1.7369599999999998),
             vertex_3d(11.34425,0.0,-1.7369599999999998),
             vertex_3d(9.25632,0.0,-3.8248900000000003),
             vertex_3d(-9.25632,1.3017,-1.7369599999999998),
             vertex_3d(-7.1683900000000005,0.0,-1.7369599999999998),
             vertex_3d(-9.25632,-0.0,0.35097),
             vertex_3d(-9.25632,-1.3017,-1.7369599999999998),
             vertex_3d(-11.34425,0.0,-1.7369599999999998),
             vertex_3d(-9.25632,0.0,-3.8248900000000003),
       };
    constexpr inline bn::color player_ship_02_colors[] = {
             bn::color(24,24,24),
    };
    constexpr inline int player_ship_02_color_0 = 0;

    constexpr inline face_3d player_ship_02_faces_full[] = {
        face_3d(player_ship_02_vertices, vertex_3d(0.0852,-0.9493,0.3026),0,2,1,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(0.4676,-0.8759,0.1192),2,0,3,0,3),
        face_3d(player_ship_02_vertices, vertex_3d(0.3116,-0.1688,-0.9351),4,0,5,0,7),
        face_3d(player_ship_02_vertices, vertex_3d(-0.6450,0.3495,-0.6796),0,4,3,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(-0.9196,-0.3740,-0.1201),0,1,5,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(0.1139,0.9916,-0.0613),1,2,3,4,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(0.4385,0.8982,0.0317),5,1,4,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(-0.0267,0.9531,0.3014),6,7,8,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(0.3401,0.9336,0.1131),8,9,6,0,3),
        face_3d(player_ship_02_vertices, vertex_3d(0.2846,0.2447,-0.9269),10,11,6,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(-0.5730,-0.4925,-0.6550),6,9,10,0,1),
        face_3d(player_ship_02_vertices, vertex_3d(-0.9830,0.1352,-0.1243),6,11,7,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(0.2334,-0.9704,-0.0628),7,10,9,8,0,4),
        face_3d(player_ship_02_vertices, vertex_3d(0.5708,-0.8204,0.0338),11,10,7,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(-0.0852,-0.9493,0.3026),12,13,14,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4676,-0.8759,0.1192),14,15,12,0,1),
        face_3d(player_ship_02_vertices, vertex_3d(-0.3116,-0.1688,-0.9351),16,17,12,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(0.6450,0.3495,-0.6796),12,15,16,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(0.9196,-0.3740,-0.1201),12,17,13,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(-0.1139,0.9916,-0.0613),13,16,15,14,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4385,0.8982,0.0317),17,16,13,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(0.0267,0.9531,0.3014),18,20,19,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(-0.3401,0.9336,0.1131),20,18,21,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(-0.2846,0.2447,-0.9269),22,18,23,0,4),
        face_3d(player_ship_02_vertices, vertex_3d(0.5730,-0.4925,-0.6550),18,22,21,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(0.9830,0.1352,-0.1243),18,19,23,0,7),
        face_3d(player_ship_02_vertices, vertex_3d(-0.2334,-0.9704,-0.0628),19,20,21,22,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(-0.5708,-0.8204,0.0338),23,19,22,0,4),
        face_3d(player_ship_02_vertices, vertex_3d(0.5210,0.6762,0.5210),24,25,26,0,7),
        face_3d(player_ship_02_vertices, vertex_3d(0.5573,-0.8149,-0.1593),27,28,29,26,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(-0.5573,-0.8149,-0.1593),28,27,30,31,0,7),
        face_3d(player_ship_02_vertices, vertex_3d(0.4916,-0.7188,0.4916),26,25,27,0,4),
        face_3d(player_ship_02_vertices, vertex_3d(-0.6928,0.6934,-0.1981),32,28,31,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(-0.5210,0.6762,0.5210),25,24,30,0,3),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4916,-0.7188,0.4916),25,30,27,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(0.6455,0.7636,0.0158),29,32,24,26,0,3),
        face_3d(player_ship_02_vertices, vertex_3d(0.6928,0.6934,-0.1981),28,32,29,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(-0.6455,0.7636,0.0158),24,32,31,30,0,0),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4676,0.7501,0.4676),33,34,35,0,1),
        face_3d(player_ship_02_vertices, vertex_3d(0.4676,-0.7501,0.4676),36,37,35,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(0.4676,-0.7501,-0.4676),37,36,38,0,3),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4676,-0.7501,0.4676),35,34,36,0,6),
        face_3d(player_ship_02_vertices, vertex_3d(0.4676,0.7501,-0.4676),33,37,38,0,4),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4676,0.7501,-0.4676),34,33,38,0,5),
        face_3d(player_ship_02_vertices, vertex_3d(-0.4676,-0.7501,-0.4676),34,38,36,0,2),
        face_3d(player_ship_02_vertices, vertex_3d(0.4676,0.7501,0.4676),37,33,35,0,2),
    };
    constexpr inline model_3d_item player_ship_02_full(player_ship_02_vertices, player_ship_02_faces_full, player_ship_02_colors);
    };
#endif